### ISSUE TITLE
Providing empty website url crashes application

### ISSUE THREAD

**Issue by elmccd** [sindresorhus/generator-nm#50] opened 2016-05-14 18:07 UTC
After providing empty website url (for the first time - when no default has been stored yet) generator crashes.

``` bash
? What do you want to name your module? test
? What is your GitHub username? elmccd
? What is the URL of your website? 
     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 



/home/mccd/apps/node/lib/node_modules/yo/node_modules/rx/dist/rx.js:77
    throw e;
    ^
TypeError: Parameter "url" must be a string, not object
```

The reason for that is here:

``` js
validate: x => x.length > 0 ? true : 'You have to provide a website URL',
filter: x => normalizeUrl(x)
```

It looks like normalizeUrl, which throws exception for empty string, is being ran before validating provided value.

**Comment by SamVerschueren** [comment] 2016-05-14 18:31
Did you add a space or just nothing? I guess it should be `x.trim().length` but that might not be the reason for this failure.

**Comment by elmccd** [comment] 2016-05-14 18:35
Nothing.

It looks like filter function is executed before validating value.

After removing this line from source code `filter: x => normalizeUrl(x)` and after submitting empty url I was prompt with 'You have to provide a website URL' as expected.

**Comment by sindresorhus** [comment] 2016-05-15 09:05
Seems after the latest `yeoman-generator` the order of `validate` and `filter` changed. // @SBoudrias

**Comment by kevva** [comment] 2016-05-15 18:37
Relevant commit (and issue) https://github.com/senshuu/Inquirer.js/commit/8dfc3526b78a1519b73596911c15363f69d2807e.

**Comment by sindresorhus** [comment] 2016-12-13 20:21
Can't reproduce this anymore. Must have been fixed in `Inquirer.js`.

**Closed by sindresorhus** 2016-12-13 20:21 UTC
Labels: bug
